# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김대현
title: 백엔드 엔지니어
email: sund46@naver.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  sund46
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 대현-김-7167a7263
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://uncovered-quokka-315.notion.site/41972403e8084dabaaba5efa51c40408
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/myProfile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring, Kotlin & Spring, 그리고 NodeJS & JavaScript 기술 스택과 AWS 클라우드를 기반으로 3년차 백엔드 개발자입니다. 지금까지 <b>대학교 LMS(학습관리 시스템)</b>, <b>농약사 ERP 시스템</b>, 그리고 <b>스마트 농업 서비스</b> 등에서 백엔드 플랫폼을 개발해왔습니다.

  제가 개발하는 서비스는 <mark>개발과 비즈니스 간의 원활한 커뮤니케이션</mark>을 가장 중요한 가치로 생각합니다. 문제 해결과 비즈니스 발전을 위해 능동적이고 적극적인 커뮤니케이션을 지향합니다. 이를 바탕으로 더 나은 개발자가 되기 위해 지속적으로 학습하고, 다양한 경험을 쌓으며 노력하고 있습니다.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left #top-middle
        title: (주)그린랩스
        link: https://greenlabs.co.kr/
        sub_title: Kotlin & Spring 백엔드 개발자
        caption: 2022.03 ~ 현재
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          스마트 농업 서비스
        description: | # this will include new lines to allow paragraphs
          - 재배자재 진단 및 처방 서비스 개발
          - 위치기반 시공가 및 농약사 찾기 서비스 개발
          - 시공견적 및 상담 서비스 고도화
          - 농약사 ERP의 품목, 고객, 거래내역의 데이터 파이프라인 구축 (SQS & S3 & Lambda)
          - 스마트 농업 서비스 전자영수증 개발

      - layout: left #top-middle
        title: (주)우성소프트
        link: https://wssw.kr
        sub_title: JavaScript & NodeJs 백엔드 개발자
        caption: 2021.06 ~ 2022.03
        quote: >
          1000개 이상의 고객사를 보유한 농자재 유통 전문프로그램 ERP
        description: | # this will include new lines to allow paragraphs
          - 농약사 ERP 기반 POS 서비스 API/Batch 개발 및 고도화
          - 농약사 ERP 기반 APP 서비스 API 개발
          - 운영 업무를 위한 관리자 페이지 개발

      - layout: left #top-middle
        title: (주)디유넷
        link: http://www.dunet.co.kr/
        sub_title: 웹 개발자
        caption: 2019.12 ~ 2021.06
        quote: >
          스마트러닝솔루션 LMS
        description: | # this will include new lines to allow paragraphs
          - LENS3, BLU, BLU2, BLU3 각 버전 별 시스템유지보수 및 업데이트
          - 약 20개의 대학교별 요구사항에 따른 시스템고도화
          - 비대면 강의를 위한 원격강의시스템 도입
          - 시스템 운영 및 기능적 편의를 위한 어드민 기능 개발

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: top-middle
        quote: 현재 업무에 사용중 혹은 사용했던 기술들입니다.

      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java, Kotlin, JavaScript
          - Spring MVC, Spring Boot, NodeJs, ExpressJs
          - JPA, Querydsl, Hibernate, Mybatis, Sequelize
          - Junit4/5, Mockito, Jest
          - Gradle, Maven, Npm
          - Eclipse, IntelliJ, Visual Studio Code

      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL, MariaDB, Oracle, MsSql, Tibero, DB2
          - AWS SQS, RDS (Aurora), S3, EC2, Lambda
          - Nginx, Pm2, Tomcat

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 자바(JAVA) 프레임워크 개발자 양성 과정
        sub_title: Java, Spring, JSP, Oracle 등
        caption: 2019.1 - 2019.8

      - layout: top-middle
        title: 인덕대학교 컴퓨터전자공학과
        caption: 2014.3 - 2019.2


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
